---
 - name: Ansible apt module examples
   hosts: worker
   become: true
   tasks: 
    - name: copy munge config files task
      shell: cp /data/munge.key /etc/munge/munge.key

    - name: Enable service munge 
      ansible.builtin.systemd:
        name: munge
        state: started
        enabled: yes