---
 - name: Ansible apt module examples
   hosts: crane
   become: true
   tasks: 
    - name: copy munge config files task
      shell: cp /data/munge.key /etc/munge/munge.key

    - name: Enable service munge 
      ansible.builtin.systemd:
        name: munge
        state: started
        enabled: yes

    - name: Creates slurm running directory
      file:
        path: /var/spool/slurm/d
        state: directory
        owner: slurm
        group: slurm
        mode: 0775

    - name: Restart service slurm 
      ansible.builtin.systemd:
        name: slurmd
        state: restarted